host: "127.0.0.1"
profile: "empty"

logging:
  path: "logs/events.jsonl"

web:
  enabled: true
  host: "127.0.0.1"
  port: 8000

auth:
  username: "admin"
  password: "admin123"

services:
  http_linux:
    enabled: true
    host: "0.0.0.0"
    port: 8080
  http_windows:
    enabled: true
    host: "0.0.0.0"
    port: 8082
  ssh_linux:
    enabled: true
    host: "0.0.0.0"
    port: 2222
  ftp_linux:
    enabled: true
    host: "0.0.0.0"
    port: 2121
  telnet_linux:
    enabled: true
    host: "0.0.0.0"
    port: 2323
  dns_windows:
    enabled: true
    host: "0.0.0.0"
    port: 1053
  netbios_windows:
    enabled: true
    host: "0.0.0.0"
    port: 139
  ldap_windows:
    enabled: true
    host: "0.0.0.0"
    port: 389
  ldaps_windows:
    enabled: true
    host: "0.0.0.0"
    port: 636
  mssql_windows:
    enabled: true
    host: "0.0.0.0"
    port: 1433
  rdp_windows:
    enabled: true
    host: "0.0.0.0"
    port: 3389
  smb_windows:
    enabled: true
    host: "0.0.0.0"
    port: 1445
  llmnr_windows:
    enabled: true
    host: "0.0.0.0"
    port: 5355
  nbtnns_windows:
    enabled: true
    host: "0.0.0.0"
    port: 137
